---
- hosts: localhost
  connection: local
  become: true

  vars:
    the_user: "{{ ansible_user_id }}"

  tasks:
  - name: install packages
    package:
      name:
        - curl
        - fzf
        - tmux
        - vim-nox
        - zsh

  - name: Change user shell to zsh.
    shell: chsh -s /usr/bin/zsh gw

  - name: Copy .zshrc file.
    copy:
     src: files/zsh/.zshrc
     dest: /home/gw/.zshrc
     owner: gw
     group: gw

  - name: Clone oh-my-zsh.
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh
      dest: /home/gw/.oh-my-zsh
      version: master

  - name: GW owns oh-my-zsh
    file:
      path: /home/gw/.oh-my-zsh
      recurse: yes
      owner: gw
      group: gw

  - name: Clone autosuggestions for oh-my-zsh.
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: /home/gw/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      version: master

  - name: Copy .alias file.
    copy:
     src: files/aliases/.aliases
     dest: /home/gw/.aliases
     owner: gw
     group: gw

  - name: Create .bin directory in home dir.
    file:
      path: /home/gw/.bin
      state: directory
      mode: '0755'
      owner: gw
      group: gw

  - name: Copy .tmux.conf file.
    copy:
     src: files/tmux/.tmux.conf
     dest: /home/gw/.tmux.conf
     owner: gw
     group: gw

  - name: Copy tmux-mem-cpu-load binary.
    copy:
     src: files/tmux/tmux-mem-cpu-load
     dest: /usr/local/bin/tmux-mem-cpu-load
     owner: gw
     group: root
     mode: '0755'

  - name: Create .vim/autoload directory.
    file:
      path: /home/gw/.vim/autoload
      state: directory
      mode: '0755'
      owner: gw
      group: gw

  - name: Install Plugged for vim
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /home/gw/.vim/autoload/plug.vim
      owner: gw
      group: gw
      mode: '0440'

  - name: Copy vimrc.
    copy:
     src: files/vim/.vimrc
     dest: /home/gw/.vimrc
     owner: gw
     group: gw
     mode: '0755'