---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - curl
        - fzf
        - tmux
        - vim-nox
        - zsh
    when: ansible_os_family == "Debian"

  - name: install packages
    package:
      name:
        - curl
        - tmux
        - zsh
    when: ansible_os_family == "RedHat"

  - name: Change user shell to zsh.
    shell: chsh -s /usr/bin/zsh gw

  - name: Copy .zshrc file on a Debian-Linux.
    copy:
     src: files/zsh/.zshrc_debian
     dest: /home/gw/.zshrc
     owner: gw
     group: gw
    when: ansible_os_family == "Debian"

  - name: Copy .zshrc file on a RedHat-Linux.
    copy:
     src: files/zsh/.zshrc_redhat
     dest: /home/gw/.zshrc
     owner: gw
     group: gw
    when: ansible_os_family == "RedHat"

  - name: Clone oh-my-zsh.
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh
      dest: /home/gw/.oh-my-zsh
      version: master

  - name: GW owns oh-my-zsh
    file:
      path: /home/gw/.oh-my-zsh
      recurse: yes
      owner: gw
      group: gw

  - name: Clone autosuggestions for oh-my-zsh.
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: /home/gw/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      version: master

  - name: Copy .alias file.
    copy:
     src: files/aliases/.aliases
     dest: /home/gw/.aliases
     owner: gw
     group: gw

  - name: Create .bin directory in home dir.
    file:
      path: /home/gw/.bin
      state: directory
      mode: '0755'
      owner: gw
      group: gw

  - name: Copy .tmux.conf file.
    copy:
     src: files/tmux/.tmux.conf
     dest: /home/gw/.tmux.conf
     owner: gw
     group: gw

  - name: Copy tmux-mem-cpu-load binary.
    copy:
     src: files/tmux/tmux-mem-cpu-load
     dest: /usr/local/bin/tmux-mem-cpu-load
     owner: gw
     group: root
     mode: '0755'

  - name: Create .vim/autoload directory.
    file:
      path: /home/gw/.vim/autoload
      state: directory
      mode: '0755'
      owner: gw
      group: gw

  - name: Install Plugged for vim
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /home/gw/.vim/autoload/plug.vim
      owner: gw
      group: gw
      mode: '0440'

  - name: Copy vimrc.
    copy:
     src: files/vim/.vimrc
     dest: /home/gw/.vimrc
     owner: gw
     group: gw
     mode: '0755'

  - name: Create .vim/colors directory.
    file:
      path: /home/gw/.vim/colors
      state: directory
      mode: '0755'
      owner: gw
      group: gw

  - name: Copy predawn for vim.
    copy:
     src: files/vim/predawn.vim
     dest: /home/gw/.vim/colors/predawn.vim
     owner: gw
     group: gw
     mode: '0755'

  - name: Add dirs for toprc.
    file:
      path: /home/gw/.config/procps
      state: directory
      mode: '0755'
      owner: gw
      group: gw

  - name: Copy toprc.
    copy:
     src: files/top/toprc
     dest: /home/gw/.config/procps/toprc
     owner: gw
     group: gw
     mode: '0755'
